/** domain/state: see docs/architecture.md for responsibilities. */
import { ObjMap } from '../shared/collections.js';
import { parseSearchQuery } from '../shared/search.js';

export function createComponentState() {
  return {
    documentUuid: '',
    metadata: null,
    backMatter: null,
    baseUrl: '',
    imports: [],
    importStatuses: [],
    importedDocumentUuids: {},
    components: [],
    capabilities: [],
    allEntries: [],
    entriesById: new ObjMap(),
    resourceByUuid: new ObjMap(),
    componentByUuid: new ObjMap(),
    capabilityByUuid: new ObjMap(),
    controlRefMap: {},
    capabilityComponents: {},
    componentCapabilityKeys: {},
    componentToCapabilities: {},
    searchQuery: parseSearchQuery(''),
    qRaw: '',
    types: [],
    sources: [],
    names: [],
    capabilityNames: [],
    openComponents: {},
    openCapabilities: {},
    openImplementations: {},
  };
}

export function createMappingState() {
  return {
    documentUuid: '',
    metadata: null,
    provenance: null,
    backMatter: null,
    baseUrl: '',
    entries: [],
    searchQuery: parseSearchQuery(''),
    qRaw: '',
    practices: [],
    relationships: [],
    sourceCatalogs: [],
    targetCatalogs: [],
    rationales: [],
    statuses: [],
  };
}

export function createCatalogState() {
  return {
    controls: [],
    idMap: new ObjMap(),
    uuidMap: new ObjMap(),
    edgesBase: [],
    searchQuery: parseSearchQuery(''),
    qRaw: '',
    groups: [],
    subgroups: [],
    classes: [],
    secs: [],
    targets: [],
    autoSelectedTargets: [],
    hasTargetObjectCategories: false,
    tags: [],
    efforts: [],
    modalverbs: [],
    documentations: [],
    actionwords: [],
    securityTargets: [],
    topics: [],
    topicById: new ObjMap(),
    childrenByTopic: {},
    childrenByPractice: {},
    groupRoots: [],
    groupByKey: new ObjMap(),
    groupLabelsByLevel: [{}, {}],
    controlsByGroup: {},
    ungroupedControls: [],
    openTopics: {},
    openControls: {},
    practices: [],
    practiceById: new ObjMap(),
    topicsByPractice: {},
    openPractices: {},
    openGroups: {},
    catalogGroupMode: 'none',
    catalogUuid: '',
    catalogMetadata: null,
    catalogBackMatter: null,
    catalogBaseUrl: '',
    catalogResourcesByUuid: new ObjMap(),
  };
}
